package com.mhmdawad.superest.util


const val FIRST_LOGGED_IN_APP = "FIRST_LOGGED_IN_APP"
const val USERS_COLLECTION = "Users"
const val EXPLAINED_PERMISSION = "EXPLAINED"
const val PERMISSION_ANNOTATION = "PERMISSION"
const val LOADING_ANNOTATION = "LOADING"
const val BASE_LATITUDE = 26.0
const val BASE_LONGITUDE = 32.0
const val LOCATION_ZOOM = 20f
const val COUNT_DOWN_DELAY = 60000L
const val COUNT_DOWN_INTERVAL = 1000L
